// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: last_read_comments.sql

package dbs

import (
	"context"
)

const lastReadCommentsNew = `-- name: LastReadCommentsNew :exec
INSERT INTO last_read_comments (user_id, topic_id, comment_id)
    VALUES ($1, $2, $3)
ON CONFLICT (user_id, topic_id)
    DO UPDATE SET
        comment_id = EXCLUDED.comment_id
`

type LastReadCommentsNewParams struct {
	UserID    int64
	TopicID   int64
	CommentID int64
}

func (q *Queries) LastReadCommentsNew(ctx context.Context, arg LastReadCommentsNewParams) error {
	_, err := q.exec(ctx, q.lastReadCommentsNewStmt, lastReadCommentsNew, arg.UserID, arg.TopicID, arg.CommentID)
	return err
}
