version: "3.7"

services:
  app:
    container_name: "research-forum-go-app"
    image: golang:1.21.0-alpine
    working_dir: /go/src/github.com/doutivity/research-forum-go   
    volumes:
      - .:/go/src/github.com/doutivity/research-forum-go   
    command: "sleep infinity"
    depends_on:
      - postgres1

  postgres1:
    container_name: "research-forum-go-postgres-1"
    image: postgres:16.0
    environment:
      POSTGRES_DB: "forum-db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "secretpassword"
    ports:
      - "5432:5432"